export const inventoryRoutes = [
  "/",
  "/login",
  "/subscribe",
  "/onboarding/marks",
  "/onboarding/details",
  "/dashboard",
  "/recommendations",
  "/choices",
  "/analytics",
  "/rounds",
  "/explore",
  "/explore/[code]",
  "/compare",
  "/profile/edit",
  "/admin",
  "/dataset",
  "/financials",
  "/trends",
  "/maps",
  "/notifications",
  "/reporting",
  "/data-versions",
];

export const navItems = [
  { href: "/dashboard", label: "Home", longLabel: "Dashboard" },
  { href: "/recommendations", label: "Recs", longLabel: "Recommendations" },
  { href: "/choices", label: "Choices", longLabel: "Choice Filing" },
  { href: "/compare", label: "Compare", longLabel: "College Compare" },
  { href: "/explore", label: "Explore", longLabel: "College Explorer" },
  { href: "/analytics", label: "Trends", longLabel: "Analytics" },
  { href: "/dataset", label: "Data", longLabel: "Complete Dataset" },
  { href: "/financials", label: "Finance", longLabel: "Financials" },
  { href: "/trends", label: "Discipline", longLabel: "Discipline/Trends" },
  { href: "/maps", label: "Maps", longLabel: "Map View" },
  { href: "/rounds", label: "Rounds", longLabel: "Rounds Tracker" },
  { href: "/notifications", label: "Alerts", longLabel: "Notifications" },
  { href: "/reporting", label: "Reports", longLabel: "Reporting" },
  { href: "/data-versions", label: "Versions", longLabel: "Data Versions" },
  { href: "/admin", label: "Admin", longLabel: "Operations" },
  { href: "/profile/edit", label: "Profile", longLabel: "Profile" },
];
